### ISSUE TITLE
Support for React-Native

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [dapilab/react-nice-avatar#33]
By using expo-svg you could enable the support for react-native

**Comment by zamplyy** [comment]
Hi!

FYI i made this into a react-native package.

https://www.npmjs.com/package/@zamplyy/react-native-nice-avatar

You can install is by using 
```
npm install @zamplyy/react-native-nice-avatar
```
or 
```
yarn add @zamplyy/react-native-nice-avatar
```

**Comment by NilsBaumgartner1994** [comment]
Great 👍 will check it out !


Beste Grüße,
Nils Baumgartner

**Comment by NilsBaumgartner1994** [comment]
You are using a div somewhere:

index.js:1 The above error occurred in the <div> component:
    in div (created by View)
    in View (created by ForwardRef)

**Comment by NilsBaumgartner1994** [comment]
The import statement in the doc is wrong. I created a pull request.

**Comment by NilsBaumgartner1994** [comment]
Please change same props for react-native-nice-avatars

**Comment by NilsBaumgartner1994** [comment]
Please support, since these are out of date or not working correctly.

**Comment by wwayne** [comment]
This open-sourced component is only served for web react projects, react-native is out of the scope
you can check more from https://www.npmjs.com/package/@zamplyy/react-native-nice-avatar maybe, these 2 are different projects
