### ISSUE TITLE
Update react-native-nice-avatar

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [dapilab/react-nice-avatar#34]
Out of date: https://www.npmjs.com/package/react-native-nice-avatar

**Comment by NilsBaumgartner1994** [comment]
There is missing types like: sex

**Comment by wwayne** [comment]
hi, looks that is another repo for react-native

**Comment by NilsBaumgartner1994** [comment]
Yup, saw it too now. Reopened the old issue see #33
